Repository Marzogh/SPIMemory, pull requests merged in 2019-06, with the labels that each got.

#178 Latest stable changes from development
  Change log.md
  README.md
  examples/FlashDiagnostics/FlashDiagnostics.ino
  extras/Changes.log
  extras/Library speed comparisons.xlsx
  src/SPIFlash.cpp
  src/SPIFlash.h
  src/defines.h
  src/diagnostics.cpp
  src/diagnostics.h
Labels: enhancement, feature request

#156 Make it possible to configure SPI clock right from the beginning
  src/SPIFlash.cpp
  src/SPIFlash.h
  src/SPIFlashIO.cpp
Labels: enhancement, high priority

#179 Final code for v3.4.0 from Development
  Change log.md
  README.md
  examples/FlashDiagnostics/Diagnostics_functions.ino
  examples/FlashDiagnostics/FlashDiagnostics.ino
  library.properties
  src/DMASAM.cpp
  src/DMASAM.h
  src/SPIFlash.cpp
  src/SPIFlash.h
  src/SPIFlashIO.cpp
  src/SPIFlashSFDP.cpp
  src/SPIFram.cpp
  src/SPIFram.h
  src/SPIFramIO.cpp
  src/SPIMemory.cpp
  src/SPIMemory.h
  src/defines.h
  src/diagnostics.cpp
  src/diagnostics.h
Labels: minor version

#180 Final code for v3.4.0 from Stable
  Change log.md
  README.md
  examples/FlashDiagnostics/Diagnostics_functions.ino
  examples/FlashDiagnostics/FlashDiagnostics.ino
  extras/Changes.log
  extras/Library speed comparisons.xlsx
  library.properties
  src/DMASAM.cpp
  src/DMASAM.h
  src/SPIFlash.cpp
  src/SPIFlash.h
  src/SPIFlashIO.cpp
  src/SPIFlashSFDP.cpp
  src/SPIFram.cpp
  src/SPIFram.h
  src/SPIFramIO.cpp
  src/SPIMemory.cpp
  src/SPIMemory.h
  src/defines.h
  src/diagnostics.cpp
  src/diagnostics.h
Labels: minor version
